# Generated by Django 5.1.6 on 2025-02-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_aboutus_banner_alter_blogpost_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
