# Generated by Django 5.1.6 on 2025-02-27 06:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
