# Generated by Django 5.1.6 on 2025-02-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_aboutus_content_alter_contactus_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='img',
            new_name='image',
        ),
    ]
