# Generated by Django 5.1.6 on 2025-03-04 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_img_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
